---
name: Tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        type: choice
        required: true
        description: Select type of tests
        options:
          - flake8
          - py310
  workflow_call:
    inputs:
      test_type:
        required: true
        type: string

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    environment: test-env
    env:
      SITEPACKAGES: true
    container:
      image: ghcr.io/mkulik-rh/modulemd_tools-ci:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: ${{ github.event.inputs.test_type }}
        if: "${{ github.event.inputs.test_type != '' }}"
        run: |
          tox -vvv -e ${{ github.event.inputs.test_type }}
      - name: ${{ inputs.test_type }}
        if: "${{ inputs.test_type != '' }}"
        run: |
          tox -vvv -e ${{ inputs.test_type }}
